version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-updater"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-difb6mdbrik"
s3_prefix = "stock-updater"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
